### ISSUE TITLE
Functions (java) that return an array of blocks are parsed as string

### ISSUE THREAD

**Issue by Tinkot** [btk5h/skript-mirror#100]
It will simply return the array as a string instead of a list variable. I couldn't find in the documentation how to do it so maybe i'm just not doing it correctly. See code below

```
Import:
	org.bukkit.event.entity.EntityExplodeEvent

on EntityExplodeEvent:
	set {_list::*} to event.blockList()
	broadcast "%{_list::*}%"
```

Result of code:
![](https://image.ibb.co/gvMc70/Schermafbeelding-2018-11-14-om-13-29-30.png)

**Server information**
spigot 		1.8.8 (same bug using paper)
skript 		2.2-dev35b
TuSKe 		1.8.3-PikachuPatch-v3.
Skript-Yaml 	1.2.4 
SkriptJSON 	1.0.0 
Reqn		1.2.1
Skript-db		0.1.1 
Skript-Mirror 	0.19.1

**Comment by Pikachu920** [comment]
It's not a bug and it doesn't return a string... it returns an array that you've converted to a string by broadcasting it. You need to use the spread expression (...) to turn it into a skript list.

**Comment by Tinkot** [comment]
Thanks, i didn't know that.
