### ISSUE TITLE
Delayed Effects and Events

### ISSUE THREAD

**Issue by kulkalkul** [btk5h/skript-mirror#106]
**Describe the bug**
Delayed effects don't affect AsyncPlayerPreLoginEvent and PlayerLoginEvent.

**To reproduce**
Simply using an effect with a delay on these events reproduces it. I didn't test it on other events, but this might also be a case for the others.
```
import:
	org.bukkit.event.player.AsyncPlayerPreLoginEvent
	org.bukkit.event.player.AsyncPlayerPreLoginEvent$Result

expression last delay:
	get:
		set {_delay} to {delay}
		delete {delay}
		return {_delay}
	set:
		set {delay} to change value
	delete:
		delete {delay}

effect delay it:
	trigger:
		delay the effect
		wait 5 seconds
		continue
		set last delay to false

on AsyncPlayerPreLoginEvent:
	broadcast "before delay"
	delay it
	broadcast "after delay"
	set {_delay} to last delay
	if {_delay} is not true:
		event.disallow(Result.KICK_WHITELIST!, "Not whitelisted.")
```

**Expected behavior**
I expect it to delay the execution of the event until effect finishes.

**Server information**
- skript-mirror: 1.0.0
- Skript: 2.2-dev37c
- Bukkit: Paper-1581
- Minecraft: 1.12.2
- Java: 1.8.0.181
- OS: Windows 10 Pro

**Additional context**
I don't know if this is a bug or "not possible feature". If there is a known way to avoid this, I would like to hear it. If this is a bug which can be fixed, I won't change my approach and keep using same code and move on, instead of finding another way of doing it. So, I would be happy to know if this is possible to fix or not.

**Comment by abandonedaccount6235** [comment]
events can't be delayed in bukkit
