### ISSUE TITLE
NPE when using the return effect without input with debug verbosity

### ISSUE THREAD

**Issue by Snow-Pyon** [btk5h/skript-mirror#107]
**Describe the bug**
As the title says, when using the return effect without an input, it throws a NPE. The code works fine regardless.

**To reproduce**
Just use the return effect in any custom syntax, in the following way:
```
expression test:
  get:
    if {test} isn't set:
      return
    return {test}
```
**Expected behavior**
It should just return null in my opinion. Although making the input obligatory wouldn't be bad since we're able to just use `stop` instead.

**Server information**
- skript-mirror: 1.0.0
- Skript: 2.3-beta1
- Bukkit: 1.13.2-R0.1-SNAPSHOT (Running Paper-469)
- Minecraft: 1.13.2
- Java: 1.8.0_181
- OS: Windows 10

**Additional context**
Here is the NPE:
https://gist.github.com/Snow-Pyon/780d41b046d5d8579a62322262fc9d9f

**Comment by Blueyescat** [comment]
I can't actually confirm this, using Skipt 2.3-beta4. It works as expected.

**Comment by Snow-Pyon** [comment]
It is because I have debug verbosity. Skript uses the Expression's toString to print the current parsed syntax in console, and since you are directly calling toString to a nullable expr, it is throwing that NPE.
