### ISSUE TITLE
target-block.getDrops(player's tool) generates error

### ISSUE THREAD

**Issue by MorkaZ** [btk5h/skript-mirror#114]
**Describe the bug**
target-block.getDrops(player's tool) is not working with any condition/effect that requires itemstack as an type. There is error thrown in console.

Used .sk script:
![image](https://user-images.githubusercontent.com/4214815/50577481-25ac2f00-0e29-11e9-9a3a-6a8ec705faac.png)

Error in console:
![image](https://user-images.githubusercontent.com/4214815/50577473-e5e54780-0e28-11e9-95e3-c1d321b898f0.png)

**Server information**
- skript-mirror: latest
- Skript: 2.3-beta7
- Bukkit: 
- Minecraft: 1.13.2
- Java: 1.8
- OS: Windows/Linux

**Comment by btk5h** [comment]
Working as intended. getDrops does not return a Skript itemstack; you must convert it yourself.

**Comment by MorkaZ** [comment]
So skript does not use bukkit's ItemsSack class? Why? Is there any easy way to parse it into right ItemStack type?

**Comment by TrademarkTM** [comment]
If you use `...event.getDrops()` it works just fine.

**Comment by Snow-Pyon** [comment]
This can be closed since it was an user error. Though, should it throw that stack trace? 
Haven't looked whether it is due to Skript itself not being able to convert it or skript-mirror failing at doing it.
