### ISSUE TITLE
Temporary variables in parse section is broken in beta6+

### ISSUE THREAD

**Issue by TrademarkTM** [btk5h/skript-mirror#115]
*It seems like #111 reports the exactly same problem. Sorry for posting it again.*
Possibly related commits:
https://github.com/SkriptLang/Skript/commit/048ce296c2c3427bbbb5f9d128d150b802de0df3
https://github.com/SkriptLang/Skript/commit/237b3dd928f3108d154204d3e98af1208e7679f4

**Describe the bug**
Since bensku's fixes to remove some memory leaks, the parse section no longer holds temporary variables.

**To reproduce**
```
expression something:
	return type: text
	parse:
		set {_a} to "sup"
		continue
	get:
		return {_a}
```

**Expected behavior**
The variables should be kept?

**Server information**
- skript-mirror: 1.0.0
- Skript: beta7
- Bukkit: Paper
- Minecraft: 1.13.2
- Java: 8 191
- OS: Windows 10

**Additional context**
The same problem goes for the `await` effect.
If you use something like this:
```
set {_b} to diamond sword
await Bukkit.broadcastMessage("%{_b}%")
```
`{_b}` is simply displayed as `<none>`.

Hope this can be fixed.
Thanks!

**Comment by bensku** [comment]
SkriptLang/Skript@237b3dd is probably the main culprit. It fixed SkriptLang/Skript#1763 according to my tests, though OP still claims it was not fixed.
