### ISSUE TITLE
Methods of Methods

### ISSUE THREAD

**Issue by Cormanz** [btk5h/skript-mirror#123]
So, with Skript-Mirror, we can get methods. But, we can't get methods of methods. What do I mean by that? Let me explain.

In skript-mirror, you can do things like
**thing.method()** and **thing.method(args)** but, what you can't do is **thing.method().method()**.

I think that should be in skript-mirror since it would make code a lot shorter. You wouldn't have to set variables just to use a method of a method. Right now, you have to do 

**> represents a new line in the example**
`set {_this} to expression-1.method() > return {_this}.expression()`
I think it would be easier if we could do methods of methods and just do:
`return expression-1.method().expression()`. It is slightly more advanced and looks more tricky, but skript-mirror again is an addon for more advanced users. Thanks! Have a good day.

**Comment by btk5h** [comment]
You should already be able to do this. Do you have an example where this
doesn't work?

**Comment by Cormanz** [comment]
I just tested it right now and it looks like I'm wrong that this isn't a current feature, and that it is. I felt like I had a recent memory of it happening, looks like I'm wrong. Sorry for my misunderstanding.
