### ISSUE TITLE
Error: Invalid import statement while the import is valid

### ISSUE THREAD

**Issue by Mwexim** [btk5h/skript-mirror#127]
**Describe the bug**
When using the code below, it gives me the error: '{@nms}.Block is an invalid import statement. (script.sk, line 11: {@nms}.Block')'.
However this is a snippet from your documentation site, so it should be valid.
The second weird things is that it works on skript-mirror 1.0, but it doesn't for 2.0

**To reproduce**
```import: 
    org.bukkit.Bukkit


option nms:
    get: 
        set {_nms version} to Bukkit.getServer().getClass().getPackage().getName().split("\.")[3]
        return "net.minecraft.server.%{_nms version}%"

import:
    {@nms}.Block
```

**Expected behavior**
Normally, the Skript should just import the Block statement right.

**Screenshots**
NA

**Server information**
- skript-mirror: 2.0 
- Skript: 2.3.6
- Bukkit: Version 1.13.2
- Minecraft: Version 1.13.2
- Java: NA
- OS: NA

**Additional context**
NA

**Comment by Mwexim** [comment]
Blueyescat confirmed this

**Comment by Mwexim** [comment]
Will this not be handled?

**Comment by btk5h** [comment]
Sorry for the response time, I have a lot of other stuff on my plate right now.

I'll get to this when I have more free time and when the Skript development ecosystem feels more stable.

**Comment by Mwexim** [comment]
Okay!
