### ISSUE TITLE
Await code section

### ISSUE THREAD

**Issue by TrademarkTM** [btk5h/skript-mirror#129]
**Is your feature request related to a problem? Please describe.**
Await can only be used in single lines and with Java code. As expressions cannot be used 

**Describe the solution you'd like**
My suggestion is to make `await` similar to MundoSK's `async`, which can be used like this:
```
async:
	set {_a} to json from url "..."
	send "%{_a}%"
```

Thanks.

**Comment by btk5h** [comment]
This is outside of the scope of skript-mirror.
