### ISSUE TITLE
get player's angle

### ISSUE THREAD

**Issue by xbxymax** [btk5h/skript-mirror#131]
I want to get the direction Angle of the player (0° ~ 180°)
Can you provide some code writing

**Comment by btk5h** [comment]
You should be able to extract the pitch and yaw from a Location object. ([Documentation](https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Location.html)) If I recall correctly, this feature is also a part of Skript, so you shouldn't need skript-mirror for this.

**Comment by xbxymax** [comment]
There are two players and I want to know if player A is standing behind player B and preparing to attack him
I tried skript syntax, but failed.
		set {_a} to "xbxy" parsed as player
		set {_b} to "test" parsed as player
		set {_v1} to vector from yaw {_a}'s yaw and pitch {_a}'s pitch
		set {_v2} to vector from yaw {_b}'s yaw and pitch {_b}'s pitch
		broadcast "%angle between {_v1} and {_v2}%"
Because the code only gets one direction,
I don't know what to do next
I am not good at Java, so I tried sku BBS all night because I heard that skript-mirror can get angles

**Comment by btk5h** [comment]
This issue tracker is for skript-mirror related issues only.

I'll gladly refer you to resources that might point you in the right direction, but the problem-solving is up to you.
