### ISSUE TITLE
event error

### ISSUE THREAD

**Issue by xbxymax** [btk5h/skript-mirror#132]
look
http://haste.athion.net/axukalilec.http

**Comment by btk5h** [comment]
You seem to have a capitalization issue. You imported SyncCompleteEvent, not syncCompleteEvent.

**Comment by xbxymax** [comment]
I don't quite understand

**Comment by btk5h** [comment]
skript-mirror is case sensitive. You must copy identifier names exactly or your code will not work.

**Comment by xbxymax** [comment]
Thank you!!!!!
