### ISSUE TITLE
Array of Integer doesn't work 

### ISSUE THREAD

**Issue by uiytt** [btk5h/skript-mirror#139]
**Describe the bug**
It seems that when you try to create an array that contains Integer, it doesn't work (but don't send any errors). I have no problem with Long (normal number of skript) 

**To reproduce**
```
import:
    java.lang.Integer as JavaInteger

on load:
    set {_numbers::*} to 0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15 and 16
    set {_list} to [{_numbers::*} as JavaInteger]
    output "TEST1: %{_list}%"
    output "TEST2: %{_list}[0]%"
```

**Expected behavior**
I expected to get :
TEST1: [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16]
TEST2: 1
What I got:
TEST1: 
TEST2: < none > 

**Server information**
- skript-mirror: 2.0.0
- Skript: 2.3.7
- Bukkit: git-Spigot-1a3504a-84f3da3 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)
- Minecraft: 1.13.2
- Java: Java 1.8.0_212
- OS: Debian 9

**Comment by btk5h** [comment]
You should not have to explicitly cast a numeric array, that should be handled automatically.

**Comment by uiytt** [comment]
I get Long array automatically, not a Int array.
And I may need an Int array to call some methods

**Comment by btk5h** [comment]
The conversion is done when the function is called. You do not need to explicitly convert the array yourself.

**Comment by uiytt** [comment]
:o ok thanks for the info ^^
