### ISSUE TITLE
The semicolon effect can be used with things that aren't java calls

### ISSUE THREAD

**Issue by Pikachu920** [btk5h/skript-mirror#14]
**Issue:**
`%object%;` can be used with things that aren't java calls. This isn't a big deal, but it's just to be consistent with the try expression:
https://github.com/btk5h/skript-mirror/blob/71264a743bf9ae4158cba4712cffb8a18f0f8fb1/src/main/java/com/btk5h/skriptmirror/skript/ExprTry.java#L50-L53
___
**Versions:**
- Skript 2.2-SNAPSHOT
- PaperSpigot 8b18730
- Minecraft 1.8.8
- skript-mirror 0.7.1
___
**Script:**
```
command semicolon:
  trigger:
    {_something};
```
___
**Output:**
```
[22:59:00 INFO]: [Skript] Reloading tests.sk...
[22:59:02 INFO]: [Skript] Successfully reloaded tests.sk.
```

**Comment by btk5h** [comment]
The try expression has to error because it may reflect an issue with the order in which the expressions were parsed. On the other hand, the semicolon effect cannot be misused, which is why it does not need to error.
