### ISSUE TITLE
import static

### ISSUE THREAD

**Issue by Matocolotoe** [btk5h/skript-mirror#141]
Currently you can do the following
```
import:
    (classes)
```

My suggestion is to allow this
```
import static:
    (members)
```

**Comment by btk5h** [comment]
What do you mean?

**Comment by Matocolotoe** [comment]
Well just like when you do `import static something;`

**Comment by abandonedaccount6235** [comment]
you can't statically import a class, only members

**Comment by Matocolotoe** [comment]
fixed
