### ISSUE TITLE
skript-mirror type conversions and why casting is needed

### ISSUE THREAD

**Issue by bluelhf** [btk5h/skript-mirror#149]
**Is your feature request related to a problem? Please describe.**
So, you're using skript-mirror 2.0.0-SNAPSHOT in Paper 1.15.1. You use the org.bukkit.world#getBlockAt method to get a bukkit block, expecting to get an instance of org.bukkit.block.Block. For some reason, even when using the method that, according to the javadocs of Spigot, returns a bukkit block, skript-mirror gives you an instance of CraftBlock. This frustrates you, because the method clearly is supposed to return an instance of org.bukkit.block.Block, but it doesn't!

**Describe the solution you'd like**
Casting. That's the solution. It's that simple. A new expression like `%objects% (cast to|as) [type] %javatype%`
No existing scripts are broken, but we get a feature that works around this strange behaviour of skript-mirror. With casting, we can try our best to convert an object to any type we like! If it doesn't work, just return none.

**Describe alternatives you've considered**
Different ways of getting the block initially - no luck.

**Additional Information**
Test code:
```vb
import:
  org.bukkit.Bukkit

on block break:
  set {_spigotblock} to Bukkit.getWorld("%player's world%").getBlockAt(player.getLocation())
  send "%class of {_spigotblock}%"
```
Output (1.15.1):
```
org.bukkit.CraftBukkit.v1_15_R1.block.CraftBlock
```

**Comment by btk5h** [comment]
CraftBlock is a Block, it implements Block. No casting is necessary.

**Comment by bluelhf** [comment]
Follow-up: You're right, I was trying to access a non-static method from a static context, and instead of throwing the expected error (Non-static method cannot be referenced from a static context).. So, I guess that'd be something to add if it doesn't already exist. I appreciate the quick response, though!


Kurzgesagt, I was being dumb, and is it possible to have `Non-static method cannot be referenced from a static context` be thrown instead of just the usual unknown method error? That was confusing me here.
