### ISSUE TITLE
Error when loading script.... But there isn't one?

### ISSUE THREAD

**Issue by Thibaut040** [btk5h/skript-mirror#152]
**Describe the bug**
I loaded my script, and I got an error: 
`There's no living entity in an on bukkit event event (servertje.sk, line 542: event.getClickedInventory() = inventory of villager')`
but when I tried out my script, everything went well.

**To reproduce**
1. Load this script:
```
import:
	org.bukkit.event.inventory.InventoryClickEvent

on InventoryClickEvent:
	event.getSlot() = 2
	event.getClickedInventory() = inventory of villager
	broadcast "Yep!"
```
2. Summon a villager.
3. Trade with the villager. When you trade, you'll see the message "Yep!".

**Expected behavior**
There shouldn't be an error.

**Screenshots**
![2020-04-25_16 04 23](https://user-images.githubusercontent.com/38358953/80281884-8e01dc80-870e-11ea-9468-2837e63fb823.png)

**Server information**
- skript-mirror: Tested on: 1.0.0 and 2.0.0
- Skript: 2.5-alpha3
- Paper: 1.15.2 (build 214)
- Minecraft: 1.15.2
- Java: Java 1.8
- OS: Windows 10

**Additional context**
Should I report this to Skript?

**Comment by btk5h** [comment]
This is an issue with your script. As the warning says, there are no entities in a click event.

**Comment by Thibaut040** [comment]
I don't see the problem? There's an error, but there's nothing wrong: the script works. It's `inventory of villager`, so that's inventory (not an entity? I think?)

**Comment by btk5h** [comment]
Your script is working because it's ignoring the lines that have errors.

The "villager" part of the expression is an entity.

**Comment by Thibaut040** [comment]
Oww... Yeah.... How can I fix it? :)
Because when I use this script, I got `inventory of villager`.
```
on InventoryClickEvent:
	broadcast "%event.getClickedInventory()%"
```
