### ISSUE TITLE
Listen to an event doesn't work and crash skript-mirror

### ISSUE THREAD

**Issue by AzonFR** [btk5h/skript-mirror#155]
I use FactionsX and i try to listen to the FactionDisbandEvent but i have this error:
https://pastebin.com/zJei3hpH
And after that, all expressions in my script doesn't work anymore until i remove the event in my script
Code:

import:
  net.prosavage.factionsx.event.FactionUnClaimEvent

on FactionUnClaimEvent:
  broadcast "test"

**Comment by btk5h** [comment]
Does this issue occur when listening to events from other plugins (aside from FactionsX) or standard Bukkit events?

**Comment by AzonFR** [comment]
> Does this issue occur when listening to events from other plugins (aside from FactionsX) or standard Bukkit events?

Sorry, i just edit my message and i've add my code, the event from FactionsX extends from org.bukkit.event.Event

**Comment by btk5h** [comment]
I looked into the FactionsX plugin source, the event you are trying to listen to is missing a static `getHandlerList` method. This needs to be fixed on the FactionsX side, not the skript-mirror side.

**Comment by AzonFR** [comment]
I'll tell them if they can fix that, thanks. Can you please look for this issue?
https://github.com/btk5h/skript-mirror/issues/154

**Comment by Arliind** [comment]
@btk5h FactionsX has a closed source. Don't know how you've been able to look at their source?

**Comment by AzonFR** [comment]
> @btk5h FactionsX has a closed source. Don't know how you've been able to look at their source?

https://gyazo.com/dc3899c73e7c3b1b981a0f41bc7897e9
He looked to the archived source i think

**Comment by btk5h** [comment]
If the source I was looking at was incorrect and the plugin is closed source, there's not really much I can do on my end unless this issue can be reproduced without a dependency on FactionsX.

**Comment by Arliind** [comment]
@btk5h this is a FactionsX sided error. You can go ahead and mark this as closed/solved. We're pushing an update for this as we speak.

**Comment by AzonFR** [comment]
> If the source I was looking at was incorrect and the plugin is closed source, there's not really much I can do on my end unless this issue can be reproduced without a dependency on FactionsX.

Nevermind, it's an issue from FactionsX, thanks !
