### ISSUE TITLE
Can't use on 1.17, please update.

### ISSUE THREAD

**Issue by cheatcodes22** [btk5h/skript-mirror#160]
**Is your feature request related to a problem? Please describe.**
I have a Minecraft 1.17 server and I am trying to use the plugin. It will not work on that version of Minecraft.

**Describe the solution you'd like**
Please update plugin to 1.17

**Describe alternatives you've considered**
Maybe I should just change my server to a lower version, but 1.17 is the source of the fireworks RN

**Additional context**
![image](https://user-images.githubusercontent.com/75373435/124315489-013c8500-db42-11eb-9cae-99dbdf05d184.png)
This image is an image of my plugins on the server, and how script-mirror is deactivated

**Comment by Abwasserrohr** [comment]
There is a fork of skript-mirror that works with 1.17 for me: https://github.com/TPGamesNL/skript-reflect

**Comment by cheatcodes22** [comment]
Thanks 😁
