### ISSUE TITLE
Arrays can't be inside lists

### ISSUE THREAD

**Issue by Pikachu920** [btk5h/skript-mirror#2]
**Issue:**
Arrays can't be inside lists

**Test script:**
- **Script:**
```
function typeOf(o: objects) :: types:
  loop all types:
    if {_o::*} is loop-value:
      add loop-value to {_t::*}
  return {_t::*}
command /arrayinlist:
  trigger:
    message "---------------------------------", "Starting" and "---------------------------------" to player
    set {_array::*} to "array" and [1, 2, 3 and 4]
    message "List Type: %typeOf({_array::*})%" to player
    message "List Values: %{_array::*}%" to player
    loop {_array::*}:
      message "%loop-index%|%loop-value%, type: %typeOf(loop-value)%" to player
    message "---------------------------------" to player
```
- **Output:**
![](https://i.imgur.com/ADdR6Qb.png)

**Comment by btk5h** [comment]
It seems like Skript assumes expressions won't return arrays. I might have to create a wrapper type around arrays to solve this.

**Comment by btk5h** [comment]
It looks like arrays can be added to lists through the `add` effect, but not through the `set` effect.

**Comment by Rixic** [comment]
Seems like more of a skript issue than addon imo, but if workarounds work then I'd wait until the skript parser and other parts are rewritten, if ever.
