### ISSUE TITLE
Custom events don't get called when a lower priority listener cancels the event

### ISSUE THREAD

**Issue by Pikachu920** [btk5h/skript-mirror#24]
**Issue:**
Custom events don't get called when a lower priority listener cancels the event.
___
**Versions:**
- Skript 2.2-dev32d
- PaperSpigot 8b18730
- Minecraft 1.8.8
- skript-mirror 0.8.3
___
**Script:**
```
on flight toggle:
  cancel the event

on "org.bukkit.event.player.PlayerToggleFlightEvent" with priority lowest:
  broadcast "it was caught on lowest" #goes off

on "org.bukkit.event.player.PlayerToggleFlightEvent" with priority highest:
  broadcast "it was caught on highest" #doesn't go off
```

**Comment by btk5h** [comment]
Is this normal Bukkit behavior? Does canceling an event prevent higher priority listeners from receiving it?

**Comment by Pikachu920** [comment]
no , but it is normal skript behavior.

**Comment by btk5h** [comment]
It's normal Skript behavior because all Skript event listeners share the same priority, is it not?

**Comment by Pikachu920** [comment]
well, if you have a plugin cancelling an event on a lower priority than Skript, the corresponding skript event won't be called.
