### ISSUE TITLE
Add a parse mode called when an effect/expression is init

### ISSUE THREAD

**Issue by Pikachu920** [btk5h/skript-mirror#26]
**Request:**
Add a parse mode called when an effect/expression is init
___
**Example:**
```
parse effect testing:
  chance of 50%:
    error for "try reloading again!"
  else:
    warn for "you made it this time..."
  
on script load:
  testing
```

**Comment by Snow-Pyon** [comment]
+1 for this one, currently you could call Skript#error but that won't make the expression fail so.
