### ISSUE TITLE
Custom syntax depends on load order

### ISSUE THREAD

**Issue by bi0qaw** [btk5h/skript-mirror#27]
Currently it is not possible to use a syntax defined in the same file (#25). Furthermore it is not possible to use a syntax that is defined in a file that gets loaded after the current one. It would be nice if custom syntaxes worked like functions where these limitations do not exist.

**Comment by btk5h** [comment]
Unfortunately, this is not possible unless it is built in to the parser.

**Comment by Pikachu920** [comment]
there was talk of a preload syntax at some point
