### ISSUE TITLE
PlayerInteractEntityEvent Doesn't Work on 0.6.0

### ISSUE THREAD

**Issue by Blueyescat** [btk5h/skript-mirror#3]
Doesn't broadcast on skript-mirror 0.6.0, but works fine on 0.5.0. 
I'm tried with latest (1.12) Spigot and PaperSpigot, Skript 2.2-dev29. Also tried with different priorities.

```
on "org.bukkit.event.player.PlayerInteractEntityEvent" with priority 0:
    broadcast "Test"

**Comment by btk5h** [comment]
Is the event priority important to this bug?

**Comment by Blueyescat** [comment]
No, i edited my comment "Also tried with different priorities.". But the priority important for me :)

**Comment by Blueyescat** [comment]
Works on [v0.8.3](https://github.com/btk5h/skript-mirror/releases/tag/v0.8.3) with same server and Skript versions as i tested.
