### ISSUE TITLE
Casted array turning into an Object array instead of a Byte array

### ISSUE THREAD

**Issue by Pikachu920** [btk5h/skript-mirror#39]
**Issue:**
Casted array turning into an Object array instead of a Byte array
___
**Versions:**
- Skript 2.2-dev34
- PaperSpigot 8b18730
- Minecraft 1.8.8
- skript-mirror 0.9.0
___
**Script:**
```
loop {_l::*}:
  add 1 to {_index}
  set {_bytes::%{_index}%} to {Byte}.valueOf("%loop-value%")
  broadcast "{_bytes::%{_index}%} is a %javatype of {_bytes::%{_index}%}%"
broadcast "%javatype of ([{_bytes::*} as {Byte}])%"
```
___
**Output:**
![image](https://user-images.githubusercontent.com/28607612/37446320-59caee32-27ea-11e8-9e54-7b73a51aff5f.png)

**Comment by Syst3ms** [comment]
> An NPE occurs when getting null expression
is this a copy-paste fail, or..?

**Comment by Pikachu920** [comment]
oops

**Comment by btk5h** [comment]
What's the behavior with other types of objects?

**Comment by Pikachu920** [comment]
I guess its just completely broken now,
```
[18:24:54 INFO]: executing 'set {l::*} to "a", "b", "c" and "d"'

[18:25:05 INFO]: executing 'broadcast "%javatype of ([{l::*}])%"'
[18:25:05 INFO]: [Ljava.lang.Object;

[18:25:10 INFO]: executing 'import "java.lang.String"'

[18:25:13 INFO]: executing 'broadcast "%{string}%"'
[18:25:13 INFO]: java.lang.String

[18:25:19 INFO]: executing 'broadcast "%javatype of ([{l::*} as {String}])%"'
[18:25:19 INFO]: [Ljava.lang.Object;
```

**Comment by btk5h** [comment]
I see. This was broken in https://github.com/btk5h/skript-mirror/commit/0cfa191327ef175c8fcdee84646beba1db0f8b7a since casting now preserves null references. The array type needs to be determined from within the spread expression instead of directly returning `getArray()`.
