### ISSUE TITLE
Allow return in conditions

### ISSUE THREAD

**Issue by Pikachu920** [btk5h/skript-mirror#45]
Being limited to continue makes things longer than they have to be, for example:
```
condition %string% starts with %string%:
  check:
    if try (expr-1.startsWith(expr-2)) is true:
      continue
```
instead of
```
condition %string% starts with %string%:
  check:
    return try (expr-1.startsWith(expr-2))
```

**Comment by btk5h** [comment]
What about adding an optional boolean expression at the end of continue to
make it conditional?

**Comment by Pikachu920** [comment]
```
continue if expr-1.startsWith(expr-2)
```
would be alright. Maybe even try `continue [if (%-boolean%|<.+>)]` and try parsing the regex as a condition if there is no boolean expression
