### ISSUE TITLE
Casting always returns null

### ISSUE THREAD

**Issue by Pikachu920** [btk5h/skript-mirror#5]
**Issue:**
Casting always returns null
___
**Versions:**
- Skript 2.2-dev25
- PaperSpigot 8b18730
- Minecraft 1.8.8
- skript-mirror 0.6.0
___
**Script:**
```
on script load:
  import "java.lang.Long"
  import "java.lang.String"
  import "java.lang.Object"

command /cast:
  trigger:
    broadcast "%""String"" as {String}%||String" and "-----"
    broadcast "%1 as {Long}%||Long" and "-----"
    broadcast "%""String"" as {Object}%||Object"
```
___
**Output:**

![](https://i.imgur.com/tU50LkA.png)

**Comment by btk5h** [comment]
I believe this is caused by a Skript bug where ConvertedExpressions/variables will only properly convert to the first type in a union type.
