### ISSUE TITLE
Change cast syntax to something more verbose

### ISSUE THREAD

**Issue by Pikachu920** [btk5h/skript-mirror#54]
**Is your feature request related to a problem? Please describe.**
The cast syntax taking in objects with such a generic syntax makes it cause conflicts with a lot of other addons.

**Describe the solution you'd like**
A more verbose syntax for casting

**Comment by Blueyescat** [comment]
I didn't see any conflict but the expression has ``converted to`` alias already, or **`(%javatype%)%objects%`** lol

**Comment by Pikachu920** [comment]
Cast expression no longer exists and thus this is no longer relevant
