### ISSUE TITLE
Add way to store data relative to a specific custom syntax instance

### ISSUE THREAD

**Issue by Pikachu920** [btk5h/skript-mirror#60]
**Is your feature request related to a problem? Please describe.**
Currently, it's pretty annoying to try to store some attribute of a custom syntax that only belongs to that instance of it.

**Describe the solution you'd like**
Some syntax like:
```
effect thing:
  parse:
    set attribute "events" to ScriptLoader.getCurrentEvents()
  trigger:
    # do something involving the events at run time
```

**Comment by btk5h** [comment]
What if local variables set during parse were accessible from handlers?
