### ISSUE TITLE
Delay bug 

### ISSUE THREAD

**Issue by UzumakiYT** [btk5h/skript-mirror#62]
**Describe the bug**
if there are two players online only one will get two times "test"

**To reproduce**
`effect testing %player%:	
	trigger:
		wait 1 seconds
		send "TEST" to expression-1	
		
command teste:
	trigger:				
		loop all players:
			testing loop-player`

**Server information**
- skript-mirror: 
- Skript: dev27
- Spigot 1.8.8

**Comment by btk5h** [comment]
Duplicate of #61
