### ISSUE TITLE
Error if java calls are used as effects without semicolons

### ISSUE THREAD

**Issue by Pikachu920** [btk5h/skript-mirror#65]
**Is your feature request related to a problem? Please describe.**
Even though skript-mirror on it's own requires the semicolon, some addons like skquery and mundosk have a boolean condition which comes with the side effect of allowing java calls to be used without semicolons. 

In these cases, code can stop after the java call is run for seemingly no reason. 

While this isn't skript-mirror's fault, it would be nice if skript-mirror tried to prevent this.

**Describe the solution you'd like**
I *think* when you use an inline condition SkriptLogger#getNode will return the inline condition. During the init of a java call, you could do something like
```
if (parseResult.expr.equals(SkriptLogger.getNode().getKey()) {
  Skript.error("You must use a semicolon with java call effects!");
  return false;
}
```
to detect when it is used as an effect without a semicolon.

**Comment by btk5h** [comment]
No longer applicable since effects no longer require line terminators.
