### ISSUE TITLE
Parse regex expression returns none

### ISSUE THREAD

**Issue by Blueyescat** [btk5h/skript-mirror#66]
**Describe the bug**
The Parse Regex expression returns none always. But works on the parse time.

**To reproduce**
Run this
```vb
expression test <\d+> test:
	get:
		return regex-1
```
and **`!send "%test 1 test%"`** will send "\<none\>". This doesn't depend on the return effect also tried multiple regexes and different regexes.

**Server information**
- skript-mirror: 0.14.1
- Skript: 2.2-dev36
- Bukkit: git-Paper-1335
- Minecraft: 1.12.2
- Java: 1.8.0_101
- OS: Linux

**Comment by btk5h** [comment]
The regex expression only returns capturing groups. You'll have to surround the regex in parentheses if you want to read the entire captured pattern. This will be better documented in the future.
