### ISSUE TITLE
Java call condition does not override boolean conditions

### ISSUE THREAD

**Issue by Pikachu920** [btk5h/skript-mirror#70]
**Describe the bug**
The java call condition does not override boolean conditions

**To reproduce**
```
on script load:
	{_v}.something()
	broadcast "hi"
```
Run this with just skript and skript-mirror and all is fine. Add an addon with a `%boolean%` condition and the code will stop running before the broadcast.

**Expected behavior**
The java call condition takes precedence over boolean conditions

**Server information**
- skript-mirror: 0.15.0 
```
[23:57:53 ERROR]: #!#!   Skript: 2.2-dev35b (OUTDATED)
[23:57:53 ERROR]: #!#!   Bukkit: 1.12.2-R0.1-SNAPSHOT
[23:57:53 ERROR]: #!#!   Minecraft: 1.12.2
[23:57:53 ERROR]: #!#!   Java: 1.8.0_171 (Java HotSpot(TM) 64-Bit Server VM 25.171-b11)
[23:57:53 ERROR]: #!#!   OS: Windows 10 amd64 10.0
```

**Comment by btk5h** [comment]
Do you have a list of addons that add boolean conditions (and if possible, the fully qualified names for those classes)?

**Comment by Snow-Pyon** [comment]
As far I'm aware, only MundoSK (com.pie.tlatoani.Miscellaneous.CondBoolean) and skQuery (com.w00tmast3r.skquery.elements.conditions.CondBoolean) have such condition.
