### ISSUE TITLE
Custom Literal Support

### ISSUE THREAD

**Issue by Pikachu920** [btk5h/skript-mirror#71]
**Is your feature request related to a problem? Please describe.**
You can't make Literals which can be annoying for expressions like `new line` or `file separator`

**Describe the solution you'd like**
Custom literal support, with the same syntax as expressions but using the word `literal`.

**Comment by btk5h** [comment]
What's the benefit of literals over normal expressions?

**Comment by Pikachu920** [comment]
the same benefits the normally provide in the skript api

**Comment by btk5h** [comment]
Which are? What issues are you having with the new line and file separator
expressions?

**Comment by Blueyescat** [comment]
what is `a single piece of dirt`

**Comment by Blueyescat** [comment]
@btk5h wdym? bensku just said it i don't have more info.

@Pikachu920 btw as X of Y is also an expression it would work xD

**Comment by Pikachu920** [comment]
no it would not

**Comment by Blueyescat** [comment]
lmao https://skripthub.net/docs/?id=994

**Comment by btk5h** [comment]
Should the value of literals be cached or should they just behave like expressions with no access to the calling event?

**Comment by Pikachu920** [comment]
how about both?
```
literal something:

dynamic literal something else:
```

**Comment by btk5h** [comment]
Looking into this, literals are handled completely differently from normal expressions. Literals are parsed through the ClassInfo's parser, not by Skript's normal expression parsing system.
