### ISSUE TITLE
NMS import utility

### ISSUE THREAD

**Issue by Pikachu920** [btk5h/skript-mirror#76]
**Is your feature request related to a problem? Please describe.**
Importing NMS versions is a ugly pain because the NMS package is suffixed with the current Minecraft revision.

**Describe the solution you'd like**
Some easy way to import NMS classes, like this:
```
nms import:
  MinecraftServer
  Item
```

**Describe alternatives you've considered**
```
# assume {_version} contains nms package suffix
set {MinecraftServer} to class "net.minecraft.server.%{_version}%.MinecraftServer"
```

**Comment by Pikachu920** [comment]
alternately, replacing `%nms version%` or `%version%` with the package suffix would allow more utility with things like craftbukkit imports. you could also just add a `cb import:` section too

**Comment by btk5h** [comment]
The recommended way to import NMS classes is now by using computed options:
```
option nms:
  get: 
    set {_nms version} to Bukkit.getServer().getClass().getPackage().getName().split("\.")[3]
    return "net.minecraft.server.%{_nms version}%"

import:
  {@nms}.MinecraftServer
  {@nms}.Item
```
