### ISSUE TITLE
Does not parsed as a map

### ISSUE THREAD

**Issue by Spartan9802** [btk5h/skript-mirror#80]
**Describe the bug**
Here I use the WorldGuard getRegions() which returns a map, but skript mirror does not convert it as a list

**To reproduce**
`import:
	com.sk89q.worldguard.bukkit.WorldGuardPlugin
	ch.njol.skript.hooks.regions.WorldGuardHook
	org.bukkit.plugin.Plugin
	org.bukkit.Bukkit

on script load:
	set {WorldGuardAPI} to Bukkit.getServer().getPluginManager().getPlugin("WorldGuard")
	
	set {_world} to world "world"
	set {_region} to {WorldGuardAPI}.getRegionManager({_world}).getRegion("spawn")
	
	set {_regions::*} to ...{WorldGuardAPI}.getRegionManager({_world}).getRegions()`

**Expected behavior**
I wish I could get the list of regions 

**Screenshots**
https://puu.sh/B4bur/bc59beec41.png

**Server information**
- skript-mirror:  0.16.1
- Skript: 2.2-dev37c
- Bukkit: Spigot
- Minecraft: 1.12
- Java: 8
- OS: Debian 8

**Comment by btk5h** [comment]
Maps cannot be spread. you must spread the `keySet`, `values`, or `entrySet` of the map in order to get a list.
