### ISSUE TITLE
Can't use arrays in descriptors

### ISSUE THREAD

**Issue by HYPExMon5ter** [btk5h/skript-mirror#87]
**Describe the bug**
The title says it all

**To reproduce**
```
import:
    me.clip.placeholderapi.PlaceholderAPI
    net.md_5.bungee.api.ChatMessageType
    net.md_5.bungee.api.chat.TextComponent
    ch.njol.skript.entity.EntityType as SkriptEntityType
    org.bukkit.entity.EntityType as BukkitEntityType
    org.bukkit.potion.PotionEffect

effect (send|show) action[ ]bar %string% to %players%:
    trigger:
        set {_component} to TextComponent.fromLegacyText(expression 1)
        loop expressions 2:
            loop-value.spigot().sendMessage[ChatMessageType, net.md_5.bungee.api.chat.BaseComponent](ChatMessageType.ACTION_BAR! and {_component})
```

**Expected behavior**
Sends a actionbar to the player, it used to work on a older version of skript-mirror, however it doesn't anymore.

**Server information**
- skript-mirror: 0.17.2
- Skript: Dev36
- Bukkit: 1.12.2

**Additional context**
I get this when using the effect
`14.08 23:18:04 [Server] WARN [Skript] No matching method: #sendMessage called with (ACTION_BAR (ChatMessageType), TextComponent{text=test, BaseComponent(color=, bold=null, italic=null, underlined=null, strikethrough=null, obfuscated=null, insertion=null, extra=null, clickEvent=null, hoverEvent=null)} (BaseComponent[]))`

**Comment by Pikachu920** [comment]
beat ya, #86

**Comment by HYPExMon5ter** [comment]
🤦‍♂️ lol, thank you

**Comment by btk5h** [comment]
Duplicate of #86
