### ISSUE TITLE
Java calls no longer work from Effect commands as calls are now conditions

### ISSUE THREAD

**Issue by Pikachu920** [btk5h/skript-mirror#88]
**Describe the bug**
Running `me.test()` as an effect command won't work

**To reproduce**
Run `me.test()` as an effect command

**Expected behavior**
`test` gets called

**Screenshots**
![image](https://user-images.githubusercontent.com/28607612/44130763-a2955e16-a014-11e8-8891-19bb54f211b6.png)

**Comment by btk5h** [comment]
Already fixed in 0.17.2
