### ISSUE TITLE
Class Exception

### ISSUE THREAD

**Issue by melinstagibson** [btk5h/skript-mirror#94]
So im trying to set an itemflag via the meta with skript-mirror but it wont let me and this is what i get:

`[Skript] method CraftMetaItem#addItemFlags called with (HIDE_ENCHANTS (ItemFlag[])) threw a ClassCastException: Cannot cast [Lorg.bukkit.inventory.ItemFlag; to org.bukkit.inventory.ItemFlag`

I have tried some ways around this like setting it to a variable first but the result persists, the flag doesn't get applied
here is a code example:

```
command /meta:
        trigger:
                set {mcoin} to "emerald" parsed as item
                set {_meta} to {mcoin}.getItemMeta()
                {_meta}.setUnbreakable(true)
                {_meta}.addEnchant(Enchantment.ARROW_FIRE!, 10, true)
                {_meta}.addItemFlags([ItemFlag.HIDE_ENCHANTS!])
                {mcoin}.setItemMeta({_meta})
                give 1 of {mcoin} to player
```
Im using skript-mirror 0.18.0, paperspigot 1.13.1 #238 and Skript 2.3-alpha3

**Comment by btk5h** [comment]
I can't replicate this. Does anyone else get this issue?

I'm using an older version of Spigot for 1.12, did anything in the API change that might have caused this?

**Comment by melinstagibson** [comment]
You used the same code? i tried this on 1.12.2 aswell now and get the same error

**Comment by btk5h** [comment]
Nevermind, it turns out the development build of skript-mirror has this fixed already. This should be completely fixed in the next update.
