### ISSUE TITLE
Error reloading folder containing custom expression/effect

### ISSUE THREAD

**Issue by ShaneBeee** [btk5h/skript-mirror#95]
**Describe the bug**
Im not sure if this is a Skript or a Mirror issue, 
But when I have a skript in a folder, and reload the folder I get an error.
If I reload the skripts individually ex:
```
/sk reload ehm/gravity
```
its fine.... but when I reload the folder:
```
/sk reload ehm/
```
I get this error (https://paste.md-5.net/cejexudaxu.cs)
and yes, I have a couple custom expression/effects in there

Also: Reloading ALL skripts via /sk reload scripts, does not produce this error

**To reproduce**
Put a couple scripts into a folder, reload the folder /sk reload folder/

**Expected behavior**
Not run the error ;) I would hope that reloading the folder would work just the same as reloading an individual script

**Screenshots**
None needed.... see hastebin
(https://paste.md-5.net/cejexudaxu.cs)

**Server information**
- skript-mirror: skript-mirror version 0.18.0
- Skript: [Skript: 2.2-dev37c
- Bukkit: 1.12.2-R0.1-SNAPSHOT (Spigot, last 1.12.2 build)
This server is running CraftBukkit version git-Spigot-2cf50f0-2b93d83 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT) .. This is a final build for 1.12.2. 
- Minecraft: 1.12.2
- Java: 1.8.0_181 (Java HotSpot(TM) 64-Bit Server VM 25.181-b13)
- OS: Mac OS X x86_64 10.14

**Additional context**
Nothing else I can think of

**Comment by btk5h** [comment]
Do you have more details? I can't reproduce this.

**Comment by ShaneBeee** [comment]
Im going to set up another environment. See If I can re-produce it that way.

**Comment by ShaneBeee** [comment]
OMG IM SO freaking stupid, sorry to waste your time. It turns out I had the same custom effect in 2 files.... my Apologies!
