### ISSUE TITLE
Yaw of location

### ISSUE THREAD

**Issue by Zedify** [btk5h/skript-mirror#96]
Getting locations with methods using skript-mirror will sometimes give the wrong value for Yaw and probably pitch also. The Yaw will go negative and the only solution I found was adding the Yaw to 360 if the yaw was negative.
`on any move:
	set {_T} to event.getTo()
	broadcast "%yaw of {_T}%`

**Comment by btk5h** [comment]
This is the correct behavior, since yaw in Minecraft ranges from -180 to 180 degrees. Using `Location#getYaw()` may return a negative value, though Skript's yaw expression should still return a positive value. Is this the case?

**Comment by Zedify** [comment]
Yes 
Yaw of player's location returns positive but
yaw of event.getTo() returns negative sometimes

**Comment by btk5h** [comment]
This may be a Skript issue. skript-mirror just returns a location, Skript is responsible for adjusting the yaw to a value between 0 and 360. I suggest reporting this on Skript's issue tracker and going from there.

**Comment by Zedify** [comment]
Okay thanks

**Comment by Zedify** [comment]
The yaw can also return over 360 and under -360 though is that normal?

**Comment by btk5h** [comment]
Yes, skript-mirror is just returning what the method is returning and does not normalize any values.
