### ISSUE TITLE
Incorrect Yaw

### ISSUE THREAD

**Issue by Zedify** [btk5h/skript-mirror#97]
Okay after some more testing im sure there is a definite bug with skript-mirror returning the correct yaw. It's really inconsistent but definitely wrong. Using skript's yaw of or skript-mirror's reflection to get yaw will provide different but both wrong values. If its a location not retrieved by skript-mirror the issue doesn't persist.
`on any move:
	set {_T} to event.getTo()
	broadcast "&a%yaw of {_T}% %{_T}.getYaw()%"
	set {_L} to player's location
	broadcast "&e%yaw of {_L}% %{_L}.getYaw()%"`

https://gyazo.com/eaf374fd407d8de0f4dff495e15e1232

**Comment by Zedify** [comment]
Its really inconsistent also, Opening three minecraft windows, i couldnt get it to happen on one window, but on the others it happened everytime

**Comment by Zedify** [comment]
Okay after moving for awhile all three minecraft instances give the wrong yaw.

**Comment by btk5h** [comment]
The yaw expression not working is most likely a Skript issue. Again, skript-mirror is just returning what the method is providing, so you're probably just running into some strange quirks with how the server behaves.
